### ISSUE TITLE
Missing Favicon

### ISSUE THREAD

**Issue by Anupam-Panwar** [manankohlii/spacex-launch-data#1]
* Favicon is missing 
* It is a great way to customize the website

![image](https://user-images.githubusercontent.com/65714751/120748880-1dd4a580-c521-11eb-908b-e51d93ee5c5b.png)

* I would like to work on this

**Comment by cnu1812** [comment]
added favicon

**Comment by marizvi** [comment]
Hi,
I have generated a pull request after working on this issue, kindly go through it and let me know if any changes required.

**Comment by marizvi** [comment]
And I am sorry, 
I didn't knew that we have to first ask before working on any issue, I thought it will be like first come first serve.
Kindly accept my pull request this time, from now onwards I will be taking care of it.

**Comment by marizvi** [comment]
I am already a member of LGM SOC'21

**Comment by manankohlii** [comment]
@marizvi no problem be careful next time.
Issue resolved, closing this.
