### ISSUE TITLE
Logo Addition

### ISSUE THREAD

**Issue by Ruchi-163** [manankohlii/spacex-launch-data#100]
Logo for Website

![Screenshot 2021-06-18 at 4 55 49 PM](https://user-images.githubusercontent.com/78250934/122580992-317d2180-d074-11eb-8db4-9cb780552df0.png)

**Comment by manankohlii** [comment]
@Ruchi-163 yes this is good for now, this needs to be added to the website now. Do you want me to assign you? If possible message me on discord.

**Comment by Ruchi-163** [comment]
Sure
Please assign this to me.
i will add it to the website.
