### ISSUE TITLE
Nav bar responsive

### ISSUE THREAD

**Issue by manankohlii** [manankohlii/spacex-launch-data#102]
## Describe the bug/feature
Nav bar should be like this only on smaller screen resolutions. Needs to be a transparent nav bar on bigger screens like here. On top above the search bar and on the right side of the website, three options Launches, Cores and Rockets need to be adjacent.
![Screenshot (20)](https://user-images.githubusercontent.com/43683368/122638855-796b6b00-d0ab-11eb-82f0-be55a65f2dce.png)

**Comment by jigar-sable** [comment]
Please assign me this issue.

**Comment by manankohlii** [comment]
@jigar-sable assigned.
