### ISSUE TITLE
Automatic Updation of Footer Copyright Year

### ISSUE THREAD

**Issue by Shaishav0507** [manankohlii/spacex-launch-data#103]
## Describe the bug/feature

Hey @manankohlii 
I would like to make changes in the footer copyright year, where it will automatically update itself, no need to change everytime.
Please assign it to me.
Thanks 

## Logs

If applicable, add logs to help explain your problem (e.g. the error message and/or exception traceback).

## Environment (please complete the following information):

- OS:
- Browser:

**Comment by manankohlii** [comment]
@Shaishav0507 go ahead.
