### ISSUE TITLE
Error in the step 6 of contribution Guidelines

### ISSUE THREAD

**Issue by Shaishav0507** [manankohlii/spacex-launch-data#105]
## Describe the bug/feature

Hey @manankohlii 
There is a error in the step 6 of contribution guidelines.
The repo main branch is master not main.
Please assign it to me.
Thanks.

It should be master instead of main

## Logs

If applicable, add logs to help explain your problem (e.g. the error message and/or exception traceback).

## Environment (please complete the following information):

- OS:
- Browser:

**Comment by manankohlii** [comment]
@Shaishav0507 make a PR directly. Closing.
