### ISSUE TITLE
Update the footer design.

### ISSUE THREAD

**Issue by tjanhvi** [manankohlii/spacex-launch-data#109]
## Describe the bug/feature

Want to add some some things to footer design..
## Logs

If applicable, add logs to help explain your problem (e.g. the error message and/or exception traceback).

## Environment (please complete the following information):

- OS:
- Browser:

**Comment by harshita9621** [comment]
Hi,I would like to work on this issue.

**Comment by manankohlii** [comment]
@tjanhvi go ahead.

**Comment by tjanhvi** [comment]
okay :) 
Please Mention the tag ...........

**Comment by skpandey885** [comment]
Hey Is This Still Open? If It is then Please Assign This Issue To Me Under LGMSoC'21!

**Comment by tjanhvi** [comment]
> Hey Is This Still Open? If It is then Please Assign This Issue To Me Under LGMSoC'21!

Hey, i'm doing this
