### ISSUE TITLE
Removing insecure links

### ISSUE THREAD

**Issue by manankohlii** [manankohlii/spacex-launch-data#112]
## Describe the bug/feature
These links need to be substituted in index.html with secure ones. Should not affect the website layout. See ss attached for reference.
![Screenshot (25)](https://user-images.githubusercontent.com/43683368/122785837-8ed9c400-d268-11eb-8df4-8420939a071d.png)

**Comment by Albert-Jokelin** [comment]
Hey! Can I work on this issue?

**Comment by manankohlii** [comment]
Sure @Albert-Jokelin
