### ISSUE TITLE
Mission patch image link expired on homepage

### ISSUE THREAD

**Issue by supzi-del** [manankohlii/spacex-launch-data#115]
## Describe the bug/feature
The link for the mission 1 on homepage no longer exists.

## To Reproduce

A proper link to image should be provided.

## Logs

If applicable, add logs to help explain your problem (e.g. the error message and/or exception traceback).

## Environment (please complete the following information):

- OS: Windows
- Browser: Chrome

## Additional context

![Screenshot (274)](https://user-images.githubusercontent.com/78655439/122983823-01a68480-d3ba-11eb-88c7-1e8fb1a8a19f.png)

**Comment by supzi-del** [comment]
I would like to work on this under LGMSOC.

**Comment by manankohlii** [comment]
@supzi-del it is working fine for me. Try pulling the latest changes. Closing this.
