### ISSUE TITLE
rocket page 

### ISSUE THREAD

**Issue by nitishapiplani** [manankohlii/spacex-launch-data#128]
as per now rocket button on nav bar is not redirecting to any page i would like to make a page and ridirect that button there

**Comment by harishpansari** [comment]
I am interested in issue but I don't understand what you want changes.

**Comment by nitishapiplani** [comment]
> I am interested in issue but I don't understand what you want changes.

You are participant or mentor

**Comment by harishpansari** [comment]
participant

**Comment by manankohlii** [comment]
@nitishapiplani the page for that is yet to be added. Closing this.
