### ISSUE TITLE
designing about page

### ISSUE THREAD

**Issue by Ishigupta08** [manankohlii/spacex-launch-data#13]
i will be designing an about page for this as without about page user is not clear is what the website is for. i will be using css on to it. with preferly blue colour and purple colour.plzz assign me with this issue

**Comment by manankohlii** [comment]
Okay @Ishigupta08 give it a try! We'll see what we can do.

**Comment by Jagannath8** [comment]
Can I work on this issue? I'm a participant of LGM Soc21.

**Comment by Ishigupta08** [comment]
I am working over it...and if faces any problem then you can come up

**Comment by jatinjain001** [comment]
I would like to work on it kindly assign to me please

**Comment by asdsyd** [comment]
Hi, I would like to work on it as LGMSOC21 participant.

**Comment by jatinjain001** [comment]
I would like to work on it

**Comment by ambivert-sam** [comment]
Hey, @manankohlii I'm a participant of LGMSOC'21 can I contribute to this issue . I'll be using HTML and CSS for this can you please assign it to me?

**Comment by nitishapiplani** [comment]
hey if issue is not yet resolved assign to me
