### ISSUE TITLE
Mentor Role

### ISSUE THREAD

**Issue by shivamsingh124** [manankohlii/spacex-launch-data#131]
Hello manan,
I am shivam got an opportunity to contribute as a mentor in this project can we have a chat over LinkedIn id - shivamsingh12 about my Role and my task.
please Provide me slack link and discord link for this particular project.

**Comment by yashvidas** [comment]
Hello manan, yashvi here.
Please do provide me with mentor excess

**Comment by subhasmitapradhan** [comment]
Hello Manas, please provide me the mentor role and task.
