### ISSUE TITLE
Footer icons are small

### ISSUE THREAD

**Issue by srisatya1197** [manankohlii/spacex-launch-data#132]
The icons at the footer section are too small would like to increase them.
![SpacexMK - Google Chrome 30-06-2021 22_45_48](https://user-images.githubusercontent.com/78905067/124003974-3091ab80-d9f5-11eb-845a-b7c84189ab06.png)

**Comment by manankohlii** [comment]
Okay @srisatya1197 go ahead. Make sure you do this only for desktop view and don't make them too big.

**Comment by srisatya1197** [comment]
@manankohlii ok.

**Comment by ArihantJain123** [comment]
I want to work on this issue

**Comment by srisatya1197** [comment]
@ArihantJain123 Thank you for your interest. I'm working on this. I should have made pr yesterday due to exams I had to stop by.

**Comment by srisatya1197** [comment]
@manankohlii  Just I want to clear that I'll be inactive on github for a week(sem exams). I want to tell that if it's ok then will complete this after a week.
