### ISSUE TITLE
validation of mission number

### ISSUE THREAD

**Issue by Ishigupta08** [manankohlii/spacex-launch-data#14]
mission number in search box should always take number as input not any alphabet as far as i know . so we can use validation while takin g input and display alert on entering alpahabet. i would like to work on this.

**Comment by Ishigupta08** [comment]
did your project bascially focuses onproviding mission details or other functionality other than this can be added?

**Comment by manankohlii** [comment]
Yes @Ishigupta08 you can work on the mission number validation part.

**Comment by manankohlii** [comment]
Please do the same for negative numbers as well

**Comment by cnu1812** [comment]
I would like to work on it...

**Comment by Ishigupta08** [comment]
I am working on it..if face issue then you can

**Comment by RituCs** [comment]
I would like to work on this issue if no one is working on this.

**Comment by manankohlii** [comment]
Issue resolved. Closing.
