### ISSUE TITLE
Sound effect

### ISSUE THREAD

**Issue by pranjay-poddar** [manankohlii/spacex-launch-data#141]
## Describe the feature

Would like to add sound effects to website.

## Expected behavior

Sound effects on animations and other activities which gives a great appealing effect to website.

Please assign this task to me under DevIncept SOC

**Comment by manankohlii** [comment]
@pranjay-poddar go ahead.

**Comment by pranjay-poddar** [comment]
@manankohlii Added sound effects and animations.
