### ISSUE TITLE
Develop a Contact Form with Confirmation message

### ISSUE THREAD

**Issue by ROHAN842** [manankohlii/spacex-launch-data#143]
## Describe the bug/feature
I would like to develop a contact form for the website, also upon successful submission of contact form, user would be sent to a fresh new page on clicking Send button where the message is displayed as "Thank you We received your submission , Return ". Also on clicking to Return button of that fresh new page, user is redirected to home page.

I would like to work on this issue.

Could you please assign this issue to me under LGMSOC.

**Comment by ROHAN842** [comment]
Hey @manankohlii kindly assign this issue to me under LGMSOC

**Comment by ROHAN842** [comment]
@manankohlii please assign issue to me as the end date for LGMSOC program is 10th July and I need to finish this issue also needs to make a PR before 10th so that it can be easily merged

**Comment by manankohlii** [comment]
Hey @ROHAN842 this feature is not needed right now, we can add this later. And I believe the final date of LGMSOC has been shifted to August 10.
