### ISSUE TITLE
Footer contact-icon hover animation

### ISSUE THREAD

**Issue by akashchouhan16** [manankohlii/spacex-launch-data#146]
## To Reproduce
* `Visual Component Issue`: Can be reproduced by simply running the application via `live server` or any similar tool.

## Expected behavior
* Contact Icons have a fill colour effect on `hover`. The colours can be improved to match the overall colour scheme of the application.

## Logs

`Not applicable.`

## Environment (please complete the following information):

- OS: `Any Compatible OS`
- Browser: `Any Compatible Browser`

**Comment by Amrutha1101** [comment]
I would like to work on this issue under LGM-SOC

**Comment by akashchouhan16** [comment]
@Amrutha1101 Sure. It has been assigned to you.

**Comment by Amrutha1101** [comment]
![Screenshot (145)](https://user-images.githubusercontent.com/63070698/125157687-12147880-e18a-11eb-94af-c234738aa46f.png)
May I know if any changes to be made?

**Comment by akashchouhan16** [comment]
@Amrutha1101 The colour seems to match now but there's a `blue` underline with every icon. So, you can try and make a few more enhancement tweaks with the footer to fix that and then generate a `PR`.
