### ISSUE TITLE
logo designing of our website

### ISSUE THREAD

**Issue by Ishigupta08** [manankohlii/spacex-launch-data#15]
@manankohlii A particular logo should be common on our website. would like to design it.

**Comment by Ishigupta08** [comment]
@manankohlii In this website, we only have to give details of mission or we can extend it to make related to space.

**Comment by manankohlii** [comment]
This project was initially made just with this purpose but we can always improve upon it! If you have suggestions feel free to present them here.

**Comment by Jagannath8** [comment]
Can I work on this issue? I'm a participant of LGM Soc21.

**Comment by ambivert-sam** [comment]
Hey, @Ishigupta08 I'm a participant of LGMSOC'21 ​I would like to contribute to this issue will you please assign it to me

**Comment by ambivert-sam** [comment]
Would like to contribute to this issue as a participant of LGM Soc21.

**Comment by asdsyd** [comment]
Would like to work on this issue as a participant of LGM SoC 21.

**Comment by manankohlii** [comment]
@Ishigupta08 take one more day, else will have to assign someone else.

**Comment by Ishigupta08** [comment]
Sure

**Comment by Ishigupta08** [comment]
[
![Screenshot_20210611-125439_WhatsApp](https://user-images.githubusercontent.com/78248931/121648019-aa004300-cab4-11eb-91a4-75e65fb28809.jpg)
](url)

**Comment by Ishigupta08** [comment]
![Screenshot_20210611-125432_WhatsApp](https://user-images.githubusercontent.com/78248931/121648072-b7b5c880-cab4-11eb-8bb9-d550fdf7f033.jpg)

**Comment by Ishigupta08** [comment]
![20210611_121626](https://user-images.githubusercontent.com/78248931/121648197-de73ff00-cab4-11eb-8026-1d0db3b4ab7f.jpg)

**Comment by Ishigupta08** [comment]
@manankohlii

**Comment by manankohlii** [comment]
Hello @Ishigupta08 this is not what I have in mind right now, logos are basically small maybe used to go to the home page when on mobile. Will open this issue in the future when required.
