### ISSUE TITLE
Name of the website

### ISSUE THREAD

**Issue by Ishigupta08** [manankohlii/spacex-launch-data#16]
@manankohlii have you already selected your website name means spacex data?

**Comment by RakeshCharpe** [comment]
can I work on this issue ? and can you elaborate the issue ...

**Comment by manankohlii** [comment]
Hello, this issue does not need any work right now. The project was made with the purpose of getting data regarding SpaceX launches so the name for now will remain the same. I am closing the issue.

**Comment by RakeshCharpe** [comment]
Okay!!!
