### ISSUE TITLE
Label the details shown  regarding mission

### ISSUE THREAD

**Issue by Aniket979Kanodia** [manankohlii/spacex-launch-data#18]
It would me more informative if we add label to details shown regarding various missions.

**Comment by Aniket979Kanodia** [comment]
I would like to work on this project.
Please assign me when coding period start.

**Comment by manankohlii** [comment]
@Aniket979Kanodia I am assigning you the issue, you can make the PR when LGMSoC starts!

**Comment by Aniket979Kanodia** [comment]
Thank you for assigning me this issue.
Is there any slack or discord group available which I can connect for discussion.

**Comment by manankohlii** [comment]
Yes please join the slack channel for this project through the LGMSoC workspace in the announcements section!
