### ISSUE TITLE
Adding trigger button functionality

### ISSUE THREAD

**Issue by raunak51299** [manankohlii/spacex-launch-data#19]
I would like add the functionality of searching the mission when the Enter key is pressed.
Please assign me this issue under LGM SOC.

**Comment by manankohlii** [comment]
@raunak51299 assigned.

**Comment by harshita9621** [comment]
Hii, I would like to work on this issue as LGM SOC'21 participant from June 10. Do assign me if possible. Thank You!

**Comment by manankohlii** [comment]
@harshita9621 if the issue is not resolved in a few more days by the assignee, you may work on it.

**Comment by harshita9621** [comment]
Okay @manankohlii

**Comment by manankohlii** [comment]
I am closing this issue as it has been resolved.
