### ISSUE TITLE
Missing Nav-Bar

### ISSUE THREAD

**Issue by vanishasamriddhi** [manankohlii/spacex-launch-data#2]
- Navigation-Bar is missing
-  With the help of navigation bar, the website would have a customized and would look more appealing 
- I would like to work on it.

**Comment by Jagannath8** [comment]
Can I work on this issue? I'm a participant of LGM Soc21.

**Comment by vanishasamriddhi** [comment]
Jagannath8 I'm already working on it, and I'm also LGM Soc21

**Comment by harshita9621** [comment]
Hii, I would like to work on this issue as LGM SOC'21 participant from June 10. Do assign me if possible. Thank You!

**Comment by manankohlii** [comment]
@vanishasamriddhi take one more day else will have to assign someone else. You could work on some other issue.
