### ISSUE TITLE
Make website responsive

### ISSUE THREAD

**Issue by Kartikey0205** [manankohlii/spacex-launch-data#20]
As you can go and inspect this web page and you will find that it is not purely responsive below 350px  and will do other thing as well if you suggest something !!
please assign me  this project under LGM-soc!!

@manankohlii please assign me this

/ assign

**Comment by manankohlii** [comment]
Hello @Kartikey0205 I am assigning you the issue, for now just focus on this! And a suggestion would be to keep issue titles brief so that one can get an overview easily.

**Comment by nitishapiplani** [comment]
Hey I would like to work on this under lgm SoC plzz assingn it to me if possible 
Discord name nitisha piplani

**Comment by manankohlii** [comment]
Hello @nitishapiplani , the issue has been already assigned for now, if there are changes required after some time, we can have multiple people working on it.

**Comment by aktamoli0910** [comment]
Hi, I would like to work on this issue under LGM SOC'21. Thank You.

**Comment by manankohlii** [comment]
@Kartikey0205 please resolve the issue asap, and check for changes in the master branch.

**Comment by Kartikey0205** [comment]
Sure @manankohlii

**Comment by Kartikey0205** [comment]
@manankohlii you may close this issue as this issue is solved .
(made website completely responsive! #46)
