### ISSUE TITLE
Changing button design

### ISSUE THREAD

**Issue by jigar-sable** [manankohlii/spacex-launch-data#22]
I would like to add pointer cursor on button. Enhance Input Field and Button Design.
Add new animation to button on hover. 
Trigger function to show result as we hit enter.
Please assign me this issue under LGM SOC'21.

**Comment by manankohlii** [comment]
Hello @jigar-sable , I am making this issue about changing the button design, so you can focus just on that right now. Try to make the button border look even. Thanks!

**Comment by harshita9621** [comment]
Hii, I would like to work on this issue as LGM SOC'21 participant from June 10. Do assign me if possible. Thank You!

**Comment by aktamoli0910** [comment]
Hi, Iwould like to work on this issue under LGM SOC'21. Thank You.

**Comment by aktamoli0910** [comment]
Hi, I would like to work on this issue under LGM SOC'21. Thank You.

**Comment by Sukhseerat-Kaur** [comment]
Hey.. I would like to work on this issue as a participant in LGM SOC'21.
