### ISSUE TITLE
Sign Up/Sign In Page

### ISSUE THREAD

**Issue by Rishita11** [manankohlii/spacex-launch-data#23]
I would like to work on this under LGM-SOC 21. I plan to add a sign-up and sign-in page for the user to keep track of their search history of any related data or add a "bookmark option" to mark anything important. Please assign me this @manankohlii.

**Comment by manankohlii** [comment]
Hello @Rishita11 there is no need for such a feature right now, maybe you could contribute in some other way in a later issue. Thanks!
