### ISSUE TITLE
Testimonial Section

### ISSUE THREAD

**Issue by cnu1812** [manankohlii/spacex-launch-data#37]
Let's add a testimonial section. Assign me under LGM.

**Comment by manankohlii** [comment]
@cnu1812 please elaborate.

**Comment by cnu1812** [comment]
@manankohlii  Testimonial section is basically the user can give their feedback about our website. The top feedbacks are stored in this section. example [https://assets.justinmind.com/wp-content/uploads/2020/11/testimonial-examples-testimonial-ui.png](url).
