### ISSUE TITLE
Added Hovering and Text-Shadow Effect on Buttons

### ISSUE THREAD

**Issue by ishitakapoor26** [manankohlii/spacex-launch-data#39]
Hovering effect added in Search, View Full Article and Watch Launch buttons.

**Comment by ishitakapoor26** [comment]
@manankohlii pls assign this issue to me.

**Comment by manankohlii** [comment]
Okay @ishitakapoor26 give it a try. Search button already has hover effect, maybe do the same for the other buttons.

**Comment by ishitakapoor26** [comment]
@manankohlii pls review my pr #41. I've added hovering effect pls check.

**Comment by manankohlii** [comment]
@ishitakapoor26 your PR is not up to date with the master branch. Please make changes accordingly.

**Comment by ishitakapoor26** [comment]
sorry i didn't get u?

**Comment by manankohlii** [comment]
Issue resolved. Closing.
