### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by vanishasamriddhi** [manankohlii/spacex-launch-data#4]
- Adding Footer would help visitor to reach out to developer
- I would like to work on it.

**Comment by nitishapiplani** [comment]
I would like to work on it

**Comment by harshita9621** [comment]
Hii, I would like to work on this issue as LGM SOC'21 participant from June 10. Do assign me if possible. Thank You!

**Comment by cnu1812** [comment]
I would like to work on it...

**Comment by jayant766** [comment]
Please assign me this issue under LGMSOC'21

**Comment by manankohlii** [comment]
@vanishasamriddhi take one more day, else will have to assign someone else.

**Comment by manankohlii** [comment]
A simple footer with developer's LinkedIn and GitHub account to be added.

**Comment by anushruti11** [comment]
I would like to work on it.

**Comment by Umesh-01** [comment]
@manankohlii Should I work on this??

**Comment by manankohlii** [comment]
@anushruti11 sure go ahead.

**Comment by Umesh-01** [comment]
@manankohlii pls checkout my PR for this issue...

**Comment by Umesh-01** [comment]
Ooh sorry @anushruti11 
I started working after seeing that label **"up for grab"** , I was not aware that now it is assigned to u @anushruti11

**Comment by Umesh-01** [comment]
What should I do now?? 
Should I close my PR??
@manankohlii sir

**Comment by manankohlii** [comment]
Yes @Umesh-01 close it, be careful next time :)
