### ISSUE TITLE
shields.io features

### ISSUE THREAD

**Issue by manankohlii** [manankohlii/spacex-launch-data#43]
Updating README.md with shields.io for Pull Requests, Issue and any other relevant information.

**Comment by manankohlii** [comment]
Shields.io](https://shields.io/)

**Comment by manankohlii** [comment]
https://shields.io/

**Comment by ShwetKhatri2001** [comment]
I would like to work on this issue under LGM-SOC.

**Comment by manankohlii** [comment]
@ShwetKhatri2001 assigned.

**Comment by Ishigupta08** [comment]
What this issue means?
