### ISSUE TITLE
Add contributors to readme

### ISSUE THREAD

**Issue by SanjeevKumar22** [manankohlii/spacex-launch-data#52]
## Describe the bug/feature
Readme update

## To Reproduce

addition of contributor in readme section 
## Expected behavior

help to know about the contribution

## Logs

If applicable, add logs to help explain your problem (e.g. the error message and/or exception traceback).

## Environment (please complete the following information):

- OS:Windows
- Browser:Chrome

**Comment by manankohlii** [comment]
@SanjeevKumar22 go ahead.

**Comment by jigar-sable** [comment]
@manankohlii please assign me this issue to add contributors to readme.
### I'd done with this changes.

![image](https://user-images.githubusercontent.com/64949957/121681534-94047980-cad8-11eb-8b6a-789c802e12ee.png)

**Should it be in tabular format or it's okay with design above!**

**Comment by manankohlii** [comment]
This looks good @jigar-sable . Go ahead and make the PR.

**Comment by manankohlii** [comment]
@jigar-sable can you also add shields.io features for closed issues and PR's as well?

**Comment by jigar-sable** [comment]
> @jigar-sable can you also add shields.io features for closed issues and PR's as well?

Sure @manankohlii I'll add those too and make the PR.

**Comment by manankohlii** [comment]
If @SanjeevKumar22 does not respond by the end of the day, make the PR. But next time wait for the issue to be assigned to you.

**Comment by SanjeevKumar22** [comment]
> If @SanjeevKumar22 does not respond by the end of the day, make the PR. But next time wait for the issue to be assigned to you.

I already made PR
