### ISSUE TITLE
Back-to-Top button

### ISSUE THREAD

**Issue by nKeiros13** [manankohlii/spacex-launch-data#56]
Hi! I'm a new web developer and I want to contribute to this project by making a Back-to-Top button. It will be simple with few HTML, CSS and JS code. 
I want to add this feature since I believe this site will grow tremendously in the next few months and when the contents increase, it would be necessary to implement a back-to-top button.
I also believe it would be helpful to create a page which will display all the spacex launches and their details.
I'm a participant of LGM SOC'21 and if you would like to add this small feature plz assign me  this issue.
Thank you

**Comment by manankohlii** [comment]
Hello @nKeiros13 the feature you are suggesting is surely necessary, but not as of now maybe sometime in the future when there are new features added. You could think of contributing in some other way!

**Comment by nKeiros13** [comment]
Hey @manankohlii, thank you for your quick feedback. I just wanted to add this feature before the site became more dynamic but okay. I also wanted to enquire about the api you're using since it's giving a huge JSON file. I think instead of using that, you should use 'https://github.com/r-spacex/SpaceX-API/tree/master/docs/v4' this api since you can use the axioms and other to get better results. Just saying. 
Anyway, thank you once again for your quick response.
