### ISSUE TITLE
Add page icon on the website

### ISSUE THREAD

**Issue by harshita0802goswami** [manankohlii/spacex-launch-data#57]

**Comment by Jagannath8** [comment]
Can I work on this issue? I'm a participant of LGM Soc21.

**Comment by manankohlii** [comment]
Okay @Jagannath8 give it a try.

**Comment by harshita0802goswami** [comment]
But I raised this issue first, why didn't you assign me this?

**Comment by manankohlii** [comment]
@harshita0802goswami I didn't see your name earlier. No worries, you can work on it first. @Jagannath8 let @harshita0802goswami have a try. And always provide a description to your issue however simple it may sound.

**Comment by harshita0802goswami** [comment]
Sure!! I will keep that in mind

**Comment by harshita0802goswami** [comment]
The feature I was about to add has already been added.

**Comment by manankohlii** [comment]
@Jagannath8 please elaborate what you wanted to work on.

**Comment by Jagannath8** [comment]
Yes, feature page icon added.
