### ISSUE TITLE
Add a LICENSE file

### ISSUE THREAD

**Issue by Umesh-01** [manankohlii/spacex-launch-data#59]
## Describe the bug/feature
There is no license, it is good for an open source project to have a license.

## Expected behavior
A license like MIT License should be there...

## Environment (please complete the following information):

- OS: Windows
- Browser: Google Chrome

**Comment by Umesh-01** [comment]
@manankohlii Should I work on this Issue??

**Comment by manankohlii** [comment]
@Umesh-01 Issue resolved. Closing.
