### ISSUE TITLE
Badges problem in main README.md file

### ISSUE THREAD

**Issue by Umesh-01** [manankohlii/spacex-launch-data#60]
## Describe the bug/feature

Some badges are not working what they are intended to do.
![image](https://user-images.githubusercontent.com/83420185/121667348-cfe31300-cac7-11eb-9a5c-b6007c3db88a.png)

For example, if I am clicking on the issues badge it is not taking us to the issues page but it should.

## Expected behavior

There must be links so that anyone can go to the related web pages after clicking on the badges.

## Environment (please complete the following information):

- OS: Windows
- Browser: Google Chrome

**Comment by Umesh-01** [comment]
@manankohlii Should I work on this issue??

**Comment by manankohlii** [comment]
Okay go ahead @Umesh-01
