### ISSUE TITLE
Arrange Code Structure

### ISSUE THREAD

**Issue by jigar-sable** [manankohlii/spacex-launch-data#70]
## Describe the bug/feature
Feature

## To Reproduce
Arrange all files in proper way i.e. javascript code files in js folder same for the images and assests.

## Expected behavior
It will structured the program well.

## Logs
NA

## Environment (please complete the following information):
- OS: Windows
- Browser: Chrome

## Additional context
NA

**Comment by manankohlii** [comment]
@jigar-sable go ahead!
