### ISSUE TITLE
Showing Launch video as popup 

### ISSUE THREAD

**Issue by ShwetKhatri2001** [manankohlii/spacex-launch-data#72]
## Describe the bug/feature
We can show Launch video as popup onclick to button 'Watch Launch'

## To Reproduce
This can be implemented by making a pop-up page having video of launch which opens onclick to button and closes on click to area outside the videobox

@manankohlii Assign this issue during LGM-SOC contribution period.

**Comment by raunak51299** [comment]
Can I work on this issue under LGM SOC?

**Comment by manankohlii** [comment]
@ShwetKhatri2001 assigning you for now.
