### ISSUE TITLE
I would like to add a navigation bar 

### ISSUE THREAD

**Issue by abhijeet141** [manankohlii/spacex-launch-data#77]
## Describe the bug/feature
The navigation bar will be like three line and when we will click on it the nav bar will open

## To Reproduce
I would try to add it using bootstrap

**Comment by abhijeet141** [comment]
@manankohlii Please assign me this issue

**Comment by manankohlii** [comment]
@abhijeet141 okay give it a try, for now put the options as Launches, Rockets and Cores

**Comment by abhijeet141** [comment]
> @abhijeet141 okay give it a try, for now put the options as Launches, Rockets and Cores

Okay :)

**Comment by Aaradhana11** [comment]
I would like to contribute on this issue.
