### ISSUE TITLE
Create a Contact Us page 

### ISSUE THREAD

**Issue by Amit-45** [manankohlii/spacex-launch-data#80]
## Describe the bug/feature
The contact Us page will ask the user to enter their credentials and will contain a message box that will be filled( by users )if they need to pass on any messages related to the project.

Please assign this issue to me under the LGMSOC'21 .

**Comment by akitiashritha** [comment]
/assign

I would like to work on this issue could you please assign it to me @manankohlii

**Comment by manankohlii** [comment]
Hello @Amit-45 the website is super simple right now and if someone would really want to contact, they may use the socials given on the footer. Closing this.
