### ISSUE TITLE
 The official Space X website

### ISSUE THREAD

**Issue by Amit-45** [manankohlii/spacex-launch-data#81]
## Describe the feature

Extra button can be added in the footer of the website that would redirect us to the official SpaceX website .

**Comment by Amit-45** [comment]
Please assign this issue to me under LGMSOC'21

**Comment by manankohlii** [comment]
Okay @Amit-45 give it a try.

**Comment by sejalvasan** [comment]
Can I work on this issue under LGMSOC?
