### ISSUE TITLE
Uniform button style and font

### ISSUE THREAD

**Issue by manankohlii** [manankohlii/spacex-launch-data#82]
## Describe the bug/feature
All buttons need to have a similar look including the border and font. Watch launch and View Article buttons may look different but should look attractive.

## To Reproduce
CSS Changes

**Comment by harsh72835** [comment]
I wanted to work on this issue.

**Comment by manankohlii** [comment]
@harsh72835 go ahead

**Comment by JahnaviKashyap19** [comment]
Please assign me this issue I want to work on it.

**Comment by skpandey885** [comment]
Please Assign This Issue To Me Under LGMSoC'21!
