### ISSUE TITLE
ADD: cursor : pointer property in search button.

### ISSUE THREAD

**Issue by starrohan999** [manankohlii/spacex-launch-data#89]
## Describe the bug/feature
When we hover the search button it shows the effect but most important it cursor did not change to a pointer it remains the same.

## To Reproduce
simply add Cursor: pointer property to the .btn class in CSS code.

If applicable, add logs to help explain your problem (e.g. the error message and/or exception traceback).

## Environment (please complete the following information):

- OS: Windows 10
- Browser: Chrome, Internet explorer

**Comment by starrohan999** [comment]
Hi @manankohlii, I am LGM Soc-21 participant and I would like to contribute to this project.
please assign it to me.

**Comment by harshita9621** [comment]
ii, I would like to work on this issue as LGM SOC'21 participant . Do assign me if possible. Thank You!

**Comment by manankohlii** [comment]
@starrohan999 assigned.
