### ISSUE TITLE
Adding Card structure with transitions and animations for details

### ISSUE THREAD

**Issue by ShwetKhatri2001** [manankohlii/spacex-launch-data#9]
It's better to make a card type structure with some animations and transitions to improve user interface demonstrating mission details.

I would like to work on this issue during LGM-SOC contribution period.

**Comment by Ishigupta08** [comment]
@ShwetKhatri2001  can more than one work on the issue?

**Comment by ShwetKhatri2001** [comment]
I have some ideas and want to implement them first , may be once I done that then you can also enhance this issue

**Comment by Ishigupta08** [comment]
Oky sure, give it a try

**Comment by nitishapiplani** [comment]
I would like to work on this issue

**Comment by aktamoli0910** [comment]
Hi, I would like to work on this issue under LGM SOC'21. Thank You.
