### ISSUE TITLE
Logo for the website

### ISSUE THREAD

**Issue by manankohlii** [manankohlii/spacex-launch-data#93]
## Describe the bug/feature
Logo should be small but neat. Try to take inspiration from the SpaceX logo. This would be used to navigate to the home page of the website. You can use SpaceXMK as text to be added beisde/under the logo.

**Comment by nitishapiplani** [comment]
![s1](https://user-images.githubusercontent.com/83905949/122451154-726a2d00-cfc5-11eb-8213-3ef3b284caab.PNG)
is this logo okkay for you

**Comment by manankohlii** [comment]
@nitishapiplani it does not go wiht the colour scheme of the website. And the text is wrong.

**Comment by nitishapiplani** [comment]
can u plzz attach ss of site as i am unable to open it

**Comment by manankohlii** [comment]
[Launch SpaceX](https://launchspacex.netlify.app/)
It is there in the README

**Comment by nitishapiplani** [comment]
![s2](https://user-images.githubusercontent.com/83905949/122460250-8581fa80-cfcf-11eb-88ad-01c18565532f.PNG)
see this
![s2](https://user-images.githubusercontent.com/83905949/122460282-8dda3580-cfcf-11eb-97d7-18d43c54a4cd.PNG)

**Comment by JahnaviKashyap19** [comment]
Please assign me this issue.

**Comment by JahnaviKashyap19** [comment]
Please assign me this issue I want to work on this.

**Comment by Ruchi-163** [comment]
How about this??
Simple and goes with the theme


![Screenshot 2021-06-18 at 4 40 04 PM](https://user-images.githubusercontent.com/78250934/122552389-e4895300-d053-11eb-9002-47a482b1ac8f.png)

**Comment by manankohlii** [comment]
@Ruchi-163 Can you make the text on the right side of the rocket, and use SpaceXMK

**Comment by Ruchi-163** [comment]
Something like this?

![Screenshot 2021-06-18 at 4 55 49 PM](https://user-images.githubusercontent.com/78250934/122554032-10a5d380-d056-11eb-8f0f-c038567d3678.png)
