### ISSUE TITLE
clear search bar after searching.

### ISSUE THREAD

**Issue by marizvi** [manankohlii/spacex-launch-data#94]
Hi,
While using the website I encountered one problem in it.
As soon as user searches any mission number then that mission number remains displayed in the search bar after search is complete, so if now user wants to search another mission number, he first have to clear the the previously entered number from the search bar then have to type new mission number in search box..

Here, I would like to add one feature into this website so that as soon as search button is pressed, the text inside the search box should disappear so that user do not have to explicitly clear the text inside the search bar each time.

Kindly assign me this issue under LGMSOC'21..

**Comment by manankohlii** [comment]
Okay @marizvi go ahead.
