### ISSUE TITLE
Modification on nav

### ISSUE THREAD

**Issue by Ruchi-163** [manankohlii/spacex-launch-data#98]
on hovering on nav bar content because of bright yellow colour background the text is not that clear so i can change it a bit and give like a short transition to make it little smooth.

Would you like to assign this to me under LGMSOC'21..?

Something like this.
![Screenshot 2021-06-18 at 4 31 41 PM](https://user-images.githubusercontent.com/78250934/122551519-b7887080-d052-11eb-88a2-328374ef8e4a.png)

**Comment by manankohlii** [comment]
Okay go ahead @Ruchi-163
